### PR TITLE
Features/style updates

### PR DESCRIPTION
**Pull request by complexthings**
@twslade needs some refactoring, there's several things that can be improved upon but it's got solid improvements over what was there from a usability standpoint.

### CODE REVIEW

**Comment by complexthings** [comment]
Don't ask my why some of the commits are doubled up.

**Comment by twslade** [comment]
@complexthings the copy button doesn't work. Also, some of the styling is jacked.
image
image

**Comment by complexthings** [comment]
@twslade try again I fixed those defects.

**Comment by twslade** [comment]
Still looks funky...maybe the output window should be white if the user is getting html.

image

**Comment by complexthings** [comment]
That's super strange, that's not what I see on mine.

**Comment by complexthings** [comment]
@twslade try again sir, I believe I identified a way around this.

**Comment by twslade** [comment]
Still looks the same on mine.

**Pull request merged**
